
# curl -X GET "https://api.mercedes-benz.com/experimental/connectedvehicle_tryout/v1/vehicles/1234567890ABCD1234/doors" -H "accept: application/json" -H "authorization: Bearer a1b2c3d4-a1b2-a1b2-a1b2-a1b2c3d4e5f6"
GET https://api.mercedes-benz.com/experimental/connectedvehicle_tryout/v1/vehicles/1234567890ABCD1234/doors
accept: application/json
authorization: Bearer a1b2c3d4-a1b2-a1b2-a1b2-a1b2c3d4e5f6

###

